### ISSUE TITLE
チャットルームリスト取得時のエラー対応

### ISSUE THREAD

**Issue by takashi247** [ryo-manba/ft_transcendence#54]
チャットルームが一つも作られていない状態で/chatにアクセスすると、バックエンド側で下記のエラーが発生
```
/Users/tnishina/Programming/42/ft_transcendence/backend/node_modules/@prisma/client/runtime/index.js:30873
      throw new PrismaClientKnownRequestError(message, error2.code, this.client._clientVersion, error2.meta);
            ^
Error: 
Invalid `this.prisma.chatRoom.findMany()` invocation in
/Users/tnishina/Programming/42/ft_transcendence/backend/src/chat/chat.service.ts:26:33

  23 }): Promise<ChatRoom[]> {
  24   const { skip, take, cursor, where, orderBy } = params;
  25 
→ 26   return this.prisma.chatRoom.findMany(
The table `public.ChatRoom` does not exist in the current database.
    at RequestHandler.handleRequestError (/Users/tnishina/Programming/42/ft_transcendence/backend/node_modules/@prisma/client/runtime/index.js:30873:13)
    at RequestHandler.request (/Users/tnishina/Programming/42/ft_transcendence/backend/node_modules/@prisma/client/runtime/index.js:30856:12)
    at PrismaService._request (/Users/tnishina/Programming/42/ft_transcendence/backend/node_modules/@prisma/client/runtime/index.js:31836:16)
    at ChatGateway.handleConnection (/Users/tnishina/Programming/42/ft_transcendence/backend/src/chat/chat.gateway.ts:34:18)
```

**Comment by ryo-manba** [comment]
@takashi247 
このエラー再現できなくて困ってます。。

> The table `public.ChatRoom` does not exist in the current database.

テーブルが存在しないと書かれてるので、もしかしてmigrate実行前に試した可能性あったりします？

**Comment by takashi247** [comment]
@ryo-manba 

> テーブルが存在しないと書かれてるので、もしかしてmigrate実行前に試した可能性あったりします？

確認ありがとうございます。私の方でも気づいたら消えてました。。。
これ、試したとき、ちゃんとprismaの仕組みを理解できていなかったので、もしかしたらmigrate実行前にやってたのが原因の可能性大アリです。
手元でもエラー出なくなってるので、一旦、このイシュー、closeしちゃいますね。
ご面倒おかけしましたorz

**Comment by ryo-manba** [comment]
了解です！確認ありがとうございます！
